# Generated by Django 5.0 on 2025-02-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='number_of_positions',
            field=models.IntegerField(default=0, verbose_name='Number of Positions'),
        ),
    ]
