# Generated by Django 5.0 on 2025-02-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['-donation_date'], 'verbose_name': 'दाता', 'verbose_name_plural': 'दाताहरू'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'ordering': ['created_at'], 'verbose_name': 'कार्यक्रम तस्विर', 'verbose_name_plural': 'कार्यक्रम तस्विरहरू'},
        ),
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ठेगाना'),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='फोन नम्बर'),
        ),
        migrations.AddField(
            model_name='donor',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='टिप्पणी'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='रकम'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donation_date',
            field=models.DateField(verbose_name='दान मिति'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='नाम'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='purpose',
            field=models.CharField(max_length=200, verbose_name='उद्देश्य'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='events/', verbose_name='तस्विर'),
        ),
    ]
