# Generated by Django 5.0 on 2025-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0002_committee_number_of_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='रकम')),
                ('image', models.ImageField(blank=True, null=True, upload_to='be_a_donor_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'BeaDonor',
                'verbose_name_plural': 'BeaDonors',
                'ordering': ['-created_at'],
            },
        ),
    ]
