# Generated by Django 5.0 on 2025-02-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0003_beadonor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
